### ISSUE TITLE
Add search algorithms implementation

### ISSUE THREAD

**Issue by dhrubajyoti89** [harshitbansal373/hacktoberfest2020#246]
# ADD SEARCHING ALGORITHMS IMPLEMENTATION

## Languages:

- C++
- Java
- Python

## Algorithms:

- Binary Search
- Linear Search
- Ternary Search
- Median Search

**Comment by dhrubajyoti89** [comment]
Kindly approve and assign me with C++ @harshitbansal373

**Comment by harshitbansal373** [comment]
I'm not getting what you want to say

**Comment by dhrubajyoti89** [comment]
Can i work in this particular issue? @harshitbansal373

**Comment by harshitbansal373** [comment]
You can sort the contributed code as per the particular folders and titles like sorting, algo, etc.

**Comment by Srithanya** [comment]
Can I work on Binary search in python?

**Comment by harshitbansal373** [comment]
yes!
