### ISSUE TITLE
Organizing Algorithms by Language

### ISSUE THREAD

**Issue by choubari** [harshitbansal373/hacktoberfest2020#328]
## Organizing files 

The files are very messy, especially the ones in the root folder.

* They need to be organized depending on the programming language (one folder per language)

* For games or projects that needs multiple files, every project should be on a unique folder.

**Comment by choubari** [comment]
please assign that work to me

**Comment by harshitbansal373** [comment]
Okay, so you can keep working on that.
You can organize in folder such as  algo -> binary search -> binary_search.cpp, binary_search.py etc.
like this, you can also make cpp, python, projects folder.
It would be really helpful.
